// <auto-generated />
using System;
using InfectionsProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfectionsProject.Migrations
{
    [DbContext(typeof(InfectionsContext))]
    partial class InfectionsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4");

            modelBuilder.Entity("InfectionsProject.Models.Infection", b =>
                {
                    b.Property<Guid>("InfectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfectionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PatientIdentificationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("InfectionId");

                    b.ToTable("Infections");
                });
#pragma warning restore 612, 618
        }
    }
}
